extends: default

rules:
  line-length:
    max: 140
  truthy:
    allowed-values: ['true', 'false', 'on', 'off']
  document-start:
    present: false
  trailing-spaces: enable
  new-line-at-end-of-file: enable
  brackets:
    min-spaces-inside: 0
    max-spaces-inside: 0
